name: KarmicLotto

main: com.mitsugaru.KarmicLotto.KarmicLotto

version: 0.13

website: http://dev.bukkit.org/server-mods/karmiclotto/

description: Simple lottery system

depends: [Vault]

authors:
  - Mitsugaru

commands:
  lotto:
    description: Root command for KarmicLotto
    usage: /lotto ? - Show help on KarmicLotto

permissions:
    KarmicLotto.*:
        description: Gives access to all KarmicLotto commands
        children:
            KarmicLotto.use: true
            KarmicLotto.view: true
            KarmicLotto.create: true
            KarmicLotto.admin: true
        default: op
    KarmicLotto.use:
        description: Allows user to use lottery signs
        default: op
    KarmicLotto.view:
        description: Allows view contents of lotteries
        default: op
    KarmicLotto.create:
        description: Allows user to create lottery signs
        default: op
    KarmicLotto.admin:
        description: Allows user to administrate plugin
        default: op